# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b05a4dce4c6c658ace0bcdfdeafd911dc1016f4c3dcb10d663a99fade366ec5a6a2cc91d7e0da8cf8d4becdc749214b13af1d7bc56e297c4bcb33fa62df8af56

test:
  secret_key_base: 088198f94825864b82bb6d01a24345cceb81811edbd209a2f806cce6d337c2899d2616cc081cd2a608cdd64c632ab8c49a766f9cdcb4eaf5b0231aaa9bb782d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
